"""New field surname

Revision ID: 643b98bd8a3c
Revises: 05ed47850774
Create Date: 2022-05-03 16:37:50.609821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643b98bd8a3c'
down_revision = '05ed47850774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
