version: '2'
services:

  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - 5000:5000

  generator:
    build:
      context: generator
    stop_signal: SIGKILL

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
#    volumes:
#      - ./grafana/dashboards:/etc/grafana/dashboards
#      - ./grafana/storage:/var/lib/grafana
#      - ./grafana/provisioning:/etc/grafana/provisioning
#    user: "1000"
    ports:
      - 3000:3000