version: '3.2'
services:
  postgres:
    build:
      context: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - hw

  app:
    build:
      context: web
    stop_signal: SIGKILL
    ports:
      - '80:80'
    volumes:
      - ./web/web.py:/var/server/web.py

    networks:
      - hw
    depends_on:
      - postgres

networks:
  hw:
    driver: bridge